apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ include "app.namespace" . }}
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- range $key, $val := $.Values.extraLabels }}
    {{ $key }}: {{ $val }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }}
    spec:
      containers:
        -
          {{- if .Values.image.tag }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          {{- end }}
          name: {{ include "app.fullname" . }}
          ports:
            -
              name: {{ .Values.portName }}
              containerPort: 80
          {{- with .Values.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.fpmStatusPort }}
            {{- .Values.livenessProbeParams | toYaml | nindent 12 }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources: {{ .Values.resources |toYaml |nindent 12}}
          volumeMounts:
            -
              name: nginx-conf-volume
              mountPath: /etc/nginx/{{ .Values.nginxConfigFileName }}
              subPath: {{ .Values.nginxConfigFileName }}
            -
              name: nginx-conf-volume
              mountPath: /etc/nginx/templates/{{ .Values.websiteConfigFileName }}
              subPath: {{ .Values.websiteConfigFileName }}
          {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: regcred
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            -
              weight: 2
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "app.selectorLabels" . | nindent 20 }}
                topologyKey: kubernetes.io/hostname
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
        -
          name: nginx-conf-volume
          configMap:
            name: {{ include "app.nginxConfigMapName" . }}
      {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
      {{- end }}
